### ISSUE TITLE
Update components with new label font size

### ISSUE THREAD

**Issue by montomos** [rakuten-rex/demo-register#11]
- [ ] Update components
> - [ ] Font size to 14px by default
> - [ ] the spacing between the label and the box has been increased to 8px from 4px due to the larger font size
- [ ] Update docs
> - [ ] react-app-sample
> - [ ] zeroheight

**Comment by sanchit-mishra** [comment]
I want to work on this issue can you describe exactly what has to be done?

**Comment by claudio-moya** [comment]
hi @sanchit-mishra thanx for the message, about this issue there is no need to work on this one anymore, this and other issues was fixed on previous releases, thanx!
